### ISSUE TITLE
The menu doesn't seem to show up in Gimp 2.8 on OSX

### ISSUE THREAD

**Issue by dwa012** [greyson/gimp-android#1]
I install the plugin and restart GIMP but the plugin menu doesn't show.

**Comment by greyson** [comment]
Hi, I don't have a Mac to check it with, but it usually appears under Image | Android.

**Comment by dwa012** [comment]
@greyson not sure what the issue is. I made the script executable and placed it in the plugins directory. But doesn't seem to show up.

Not sure what to do to make them show up.

Where did you put the script to "install" it?

**Comment by greyson** [comment]
`~/.gimp-2.8/plug-ins/android.py`

**Comment by dwa012** [comment]
Still no luck. I cannot determine why it is not showing up. 
I am not even sure how to debug the plugin not registering.

I removed an alternative one in case there was a conflict, but had no effect.

**Comment by greyson** [comment]
Looks like it might be in the .app folder:

http://registry.gimp.org/node/24190

or this?

http://registry.gimp.org/node/27729

**Comment by dwa012** [comment]
Tried that. Placed it in:
/Users/<me>/Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/plug-ins

Still not registering. 

Really odd. I will keep investigating it.

**Comment by shabeepk** [comment]
Same issue for me on Windows. Can't get the Android menu to show up. Can I help in some way ?

**Comment by greyson** [comment]
If anyone knows how to fix this -- I'm a linux user only, so I really
don't have the tools or licenses to check it on other platforms. I'll
certainly accept a pull request.

**Comment by braun** [comment]
I faced the same issue on windows. Solution was to change the name of intepreter at the same begining of script: 
#!/usr/bin/env python2 -> #!/usr/bin/env python

**Comment by greyson** [comment]
Alright, thank you @braun !  As it turns out, the 'python2' doesn't seem necessary, so I have fixed this in b42cbe7243f27e1de2db91500fa8026d8b640ae1
